#pragma once
#include "Base.h"
#include "GLShader.h"
#include "Render/Shader.h"
#include "Render/Texture.h"
#include "Render/TextureVariable.h"
#include "Render/Mesh.h"
#include "Render/Model.h"
#include "Render/Material.h"
#include "Render/ShaderProgram.h"
#include "Core/Scene.h"
#include "Core/GameObject.h"
#include "Core/SdlWindow.h"
#include "Core/Color.h"
#include "Core/Camera.h"
#include "Components/MeshRenderer.h"
#include "Components/Transform.h"
#include "Lighting/Light.h"
#include "Lighting/LightManager.h"


